

<<brugia.comp, echo=FALSE>>=
we.syn.purin <- GO.annot[grepl("purine.*synthetic", GO.annot$descr),]
## we don't do heme biosynthesis like all (?) nematodes 
we.syn.riboflavin <- GO.annot[grepl("riboflavin.*synthetic", GO.annot$descr),]

we.riboflav.contigs <- unique(we.syn.riboflavin$pept_id)
we.purin.contigs <- unique(we.syn.purin$pept_id)


## purin and riboflavin de-novo syntesis should be absent in brugia  
GO.brugia <- read.delim("/home/ele/Data/454/annotation/annot8r/output_Bm/GO.csv", sep=",", header=FALSE)
names(GO.brugia) <- c("pept_id", "go_term", "pcf", "descr", "slim", "besthit", "bestscore", "bestev", "hitnum", "maxhits", "fraction") 

brugia.syn.riboflavin <- GO.brugia[grepl("riboflavin.*synthetic", GO.brugia$descr),]
brugia.syn.purin <- GO.brugia[grepl("purin.*synthetic", GO.brugia$descr),]

@ 

<<wolbachia, echo=FALSE>>=
wolbachia.df <- contig.df[contig.df$family.nr%in%"Anaplasmataceae",readable]

@ 


<<genome.compare, echo=FALSE>>=

## ## remove terms which are covered more in detail by another term
## ## (have offspring which is in the raw list
## covered <- unlist(lapply(offspring, function(x){
##   any(x%in%unlist(c(rawterms, anchestor)))}))

## term1 <- rawterms[!covered]
## anchestor <- sapply(term1, function (x) {GOBPANCESTOR[[x]]})

## IPR.annot <- read.delim("/home/ele/Data/454/annotation/backup_old/A.crassus_p4ePro.iprscan", header=FALSE)
## names(IPR.annot) <- c("pept_id", "crc64", "length", "method","db_entry", "db_descr", "start", "end", "evalue","status", "date", "ip_entry", "ip_descr", "GO_descr")
## IPR.annot$pept_id <- gsub("_1", "", IPR.annot$pept_id)

## Ce.frame <- toTable(org.Ce.egGO)
## Ce.goframeData <- data.frame(Ce.frame$go_id, Ce.frame$Evidence, Ce.frame$gene_id)
## Ce.goFrame <- GOFrame(Ce.goframeData, organism = "Caenorhabditis elegans")
## Ce.goAllFrame <- GOAllFrame(Ce.goFrame)

## Ce.gsc <- GeneSetCollection(Ce.goAllFrame, setType = GOCollection())

## Ac.frame <- as.data.frame(cbind(go_id=GO.annot$go_term,
##                                 Evidence="IEA",
##                                 gene_id=GO.annot$pept_id,
##                                 Ontology=GO.annot$pcf ))

## Ac.goFrame <- GOFrame(Ac.frame, organism="Anguillicola crassus")
## Ac.goAllFrame <- GOAllFrame(Ac.goFrame)

## Ac.gsc <- GeneSetCollection(Ac.goAllFrame, setType = GOCollection())

## Ce.onto.comp <- ontoCompare(as.list(Ce.frame$go_id),
##                         probeType="GO", plot=FALSE)

## Ac.onto.comp <- ontoCompare(as.list(Ac.frame$go_id),
##                            probeType="GO", plot=FALSE)


## foo
#save.image("annotation.Rdata")

@
