<<heme, echo=FALSE>>=

goheme <- c(heme.biosynthetic.process="GO:0006783",
            heme.oxidation="GO:0006788",
            heme.catabolic.process="GO:0042167",
            siroheme.metabolic.process="GO:0046156",
            heme.a.metabolic.process="GO:0046160",
            heme.c.metabolic.process="GO:0046162",
            heme.b.metabolic.process="GO:0046492",
            heme.o.metabolic.process="GO:0048033")

## heme metabolic
heme.contigs <- GO.annot[GO.annot$go_term%in%goheme,"pept_id"]

### Hääää? All are "heme bioSYNTHETIC proces"
GO.annot[GO.annot$go_term%in%goheme,]

heme.contigs.sure <- subset(heme.contigs, heme.contigs%in%contig.df.sure$contig)
GO.annot[GO.annot$pept_id%in%heme.contigs.sure,]



@ 
