<<respiration, echo=FALSE>>=


aer.contigs <- GO.annot[GO.annot$go_term=="GO:0009060","pept_id"]
an.contigs <-  GO.annot[GO.annot$go_term=="GO:0009061","pept_id"]

## fermentation
GO.annot[GO.annot$go_term=="GO:0006113","pept_id"]

## anoxia
GO.annot[GO.annot$go_term=="GO:0071454","pept_id"]


contig.df.sure <- contig.df[contig.df$contamination1=="valid" &
                            contig.df$contamination2%in%c("nempep4", "valid") &
                            contig.df$phylum.nr%in%c("Nematoda", "No_hit") , 
                            ]

aer.contigs.sure <- subset(aer.contigs, aer.contigs%in%contig.df.sure$contig)
an.contigs.sure <- subset(an.contigs, an.contigs%in%contig.df.sure$contig)


summary.factor(contig.df[contig.df$contig%in%aer.contigs.sure, "cluster.id"])
## 4 from cluster CL193


summary(contig.df[contig.df$contig%in%aer.contigs.sure, "coverage"])
summary(contig.df[contig.df$contig%in%aer.contigs.sure, "uniq_coverage"])


summary(contig.df[contig.df$contig%in%an.contigs.sure, "coverage"])
summary(contig.df[contig.df$contig%in%an.contigs.sure, "uniq_coverage"])



summary.factor(contig.df[contig.df$contig%in%an.contigs.sure, "cluster.id"])
## also 4 from CL193

## Not sure, these overlap:
EC.annot[EC.annot$pept_id%in%an.contigs.sure,1:3]
EC.annot[EC.annot$pept_id%in%aer.contigs.sure,1:3]

## clueless about KEGG as always...:
KEGG.annot[KEGG.annot$pept_id%in%an.contigs.sure,1:5]
KEGG.annot[KEGG.annot$pept_id%in%aer.contigs.sure,1:5]




@ 
